#!/usr/bin/env node
// data/json/*.json から data/*.ts を生成する。
// Shop 型に必要なフィールド (SHOP_FIELDS) のみ抽出し、
// geocode_source / coordinate_level / normalized_address 等は除外する。
import { execSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const JSON_DIR = join(ROOT, "data", "json");
const OUT_DIR = join(ROOT, "data");

// Shop 型に含まれるフィールド (category は実行時に注入するので除く)
const SHOP_FIELDS = ["name", "url", "address", "code", "lat", "lng", "id"];

const files = readdirSync(JSON_DIR).filter((f) => f.endsWith(".json"));
console.log(`Converting ${files.length} JSON files...`);

const generated = [];
for (const file of files) {
  const key = file.replace(/\.json$/, "");
  const raw = JSON.parse(readFileSync(join(JSON_DIR, file), "utf-8"));

  if (!Array.isArray(raw.shops)) {
    console.error(`  skip ${file}: missing "shops" array`);
    continue;
  }

  const shops = raw.shops.map((shop) => {
    const out = {};
    for (const field of SHOP_FIELDS) {
      if (!(field in shop)) {
        throw new Error(
          `${file}: shop ${shop.id ?? "?"} missing field "${field}"`,
        );
      }
      out[field] = shop[field];
    }
    return out;
  });

  const ts = `// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
// Run \`npm run build-data\` to regenerate from data/json/${file}.
import type { Shop } from "../interfaces";

const shops: Omit<Shop, "category">[] = ${JSON.stringify(shops, null, 2)};

export default shops;
`;

  const outPath = join(OUT_DIR, `${key}.ts`);
  writeFileSync(outPath, ts);
  generated.push(`data/${key}.ts`);
}

console.log(`Wrote ${generated.length} TS files. Formatting with Biome...`);
execSync(
  `npx biome format --write ${generated.map((p) => `"${p}"`).join(" ")}`,
  { cwd: ROOT, stdio: "inherit" },
);
console.log("Done.");
