// 各カテゴリの設定。新カテゴリ追加時はここに 1 エントリ追加するだけで
// データ読み込み・state 初期値・マーカー描画・チップバー/シートがすべて連動する。
export type CategoryConfig = {
  label: string; // 表示用フルラベル（例: "ラーメン百名店"）
  shortLabel: string; // チップ/トグル等で使う短いラベル
  emoji: string; // マーカー・チップに表示する絵文字
  switchColor: string; // ON 時のチップ背景色（CSS color）
  dataFile: string; // data/ 配下の JSON ファイル名
  defaultVisible: boolean; // 初期表示状態
  defaultPinned: boolean; // チップバーへの初期ピン留め状態
  section: SectionKey; // ボトムシートでのグルーピング
};

// セクション定義（ボトムシートでの並び順は宣言順）
export const SECTIONS = {
  noodles: { label: "麺類" },
  japanese: { label: "和食" },
  rice: { label: "ご飯・カレー" },
  western: { label: "洋食" },
  chinese: { label: "中華" },
  meat: { label: "肉料理" },
  bakery: { label: "パン・スイーツ" },
  drinks: { label: "カフェ・バー" },
  other: { label: "その他" },
} as const satisfies Record<string, { label: string }>;

export type SectionKey = keyof typeof SECTIONS;
export const SECTION_KEYS = Object.keys(SECTIONS) as SectionKey[];

export const CATEGORIES = {
  ramen: {
    label: "ラーメン百名店",
    shortLabel: "ラーメン",
    emoji: "🍜",
    switchColor: "#ED6C02",
    dataFile: "ramen.json",
    defaultVisible: true,
    defaultPinned: true,
    section: "noodles",
  },
  udon: {
    label: "うどん百名店",
    shortLabel: "うどん",
    emoji: "🥣",
    switchColor: "#1976D2",
    dataFile: "udon.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "noodles",
  },
  soba: {
    label: "そば百名店",
    shortLabel: "そば",
    emoji: "🥢",
    switchColor: "#37474F",
    dataFile: "soba.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "noodles",
  },
  japanese: {
    label: "日本料理百名店",
    shortLabel: "日本料理",
    emoji: "🍣",
    switchColor: "#7B1FA2",
    dataFile: "japanese.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "japanese",
  },
  curry: {
    label: "カレー百名店",
    shortLabel: "カレー",
    emoji: "🍛",
    switchColor: "#D4A017",
    dataFile: "curry.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "rice",
  },
  shokudo: {
    label: "食堂百名店",
    shortLabel: "食堂",
    emoji: "🍚",
    switchColor: "#795548",
    dataFile: "shokudo.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "rice",
  },
  italian: {
    label: "イタリアン百名店",
    shortLabel: "イタリアン",
    emoji: "🍝",
    switchColor: "#388E3C",
    dataFile: "italian.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  french: {
    label: "フレンチ百名店",
    shortLabel: "フレンチ",
    emoji: "🍷",
    switchColor: "#3F51B5",
    dataFile: "french.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  spanish: {
    label: "スパニッシュ百名店",
    shortLabel: "スパニッシュ",
    emoji: "🥘",
    switchColor: "#E64A19",
    dataFile: "spanish.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  pizza: {
    label: "ピザ百名店",
    shortLabel: "ピザ",
    emoji: "🍕",
    switchColor: "#D32F2F",
    dataFile: "pizza.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  chinese: {
    label: "中国料理百名店",
    shortLabel: "中国料理",
    emoji: "🥮",
    switchColor: "#C62828",
    dataFile: "chinese.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "chinese",
  },
  gyoza: {
    label: "餃子百名店",
    shortLabel: "餃子",
    emoji: "🥟",
    switchColor: "#F4511E",
    dataFile: "gyoza.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "chinese",
  },
  hamburger: {
    label: "ハンバーガー百名店",
    shortLabel: "ハンバーガー",
    emoji: "🍔",
    switchColor: "#6D4C41",
    dataFile: "hamburger.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  steak: {
    label: "ステーキ百名店",
    shortLabel: "ステーキ",
    emoji: "🥩",
    switchColor: "#8E0000",
    dataFile: "steak.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  bread: {
    label: "パン百名店",
    shortLabel: "パン",
    emoji: "🥖",
    switchColor: "#A1887F",
    dataFile: "bread.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "bakery",
  },
  ice_gelato: {
    label: "アイス・ジェラート百名店",
    shortLabel: "アイス",
    emoji: "🍨",
    switchColor: "#EC407A",
    dataFile: "ice_gelato.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "bakery",
  },
  cafe: {
    label: "カフェ百名店",
    shortLabel: "カフェ",
    emoji: "☕",
    switchColor: "#4E342E",
    dataFile: "cafe.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  bar: {
    label: "バー百名店",
    shortLabel: "バー",
    emoji: "🍸",
    switchColor: "#311B92",
    dataFile: "bar.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  creative_innovative: {
    label: "創作・イノベーティブ百名店",
    shortLabel: "創作",
    emoji: "✨",
    switchColor: "#00838F",
    dataFile: "creative_innovative.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "other",
  },
  okonomiyaki: {
    label: "お好み焼き百名店",
    shortLabel: "お好み焼き",
    emoji: "🥞",
    switchColor: "#FF8F00",
    dataFile: "okonomiyaki.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "other",
  },
  asia_ethnic: {
    label: "アジア・エスニック百名店",
    shortLabel: "エスニック",
    emoji: "🌶️",
    switchColor: "#558B2F",
    dataFile: "asia_ethnic.json",
    defaultVisible: false,
    defaultPinned: false,
    section: "other",
  },
} as const satisfies Record<string, CategoryConfig>;

export type CategoryKey = keyof typeof CATEGORIES;

export const CATEGORY_KEYS = Object.keys(CATEGORIES) as CategoryKey[];
