import type { Shop } from "./index";

// 各カテゴリの設定。新カテゴリ追加時はここに 1 エントリ追加するだけで
// データ読み込み・state 初期値・マーカー描画・チップバー/シートがすべて連動する。
export type CategoryConfig = {
  label: string; // 表示用フルラベル（例: "ラーメン百名店"）
  shortLabel: string; // チップ/トグル等で使う短いラベル
  emoji: string; // マーカー・チップに表示する絵文字
  switchColor: string; // ON 時のチップ背景色（CSS color）
  loader: () => Promise<{ default: Omit<Shop, "category">[] }>; // 該当カテゴリの店データを遅延ロードする
  defaultVisible: boolean; // 初期表示状態
  defaultPinned: boolean; // チップバーへの初期ピン留め状態
  section: SectionKey; // ボトムシートでのグルーピング
};

// セクション定義（ボトムシートでの並び順は宣言順）
export const SECTIONS = {
  noodles: { label: "麺類" },
  japanese: { label: "和食" },
  rice: { label: "ご飯・カレー" },
  western: { label: "洋食" },
  chinese: { label: "中華" },
  meat: { label: "肉料理" },
  bakery: { label: "パン・スイーツ" },
  drinks: { label: "カフェ・バー" },
  other: { label: "その他" },
} as const satisfies Record<string, { label: string }>;

export type SectionKey = keyof typeof SECTIONS;
export const SECTION_KEYS = Object.keys(SECTIONS) as SectionKey[];

export const CATEGORIES = {
  ramen: {
    label: "ラーメン百名店",
    shortLabel: "ラーメン",
    emoji: "🍜",
    switchColor: "#ED6C02",
    loader: () => import("../data/ramen"),
    defaultVisible: true,
    defaultPinned: true,
    section: "noodles",
  },
  udon: {
    label: "うどん百名店",
    shortLabel: "うどん",
    emoji: "🥣",
    switchColor: "#1976D2",
    loader: () => import("../data/udon"),
    defaultVisible: true,
    defaultPinned: false,
    section: "noodles",
  },
  soba: {
    label: "そば百名店",
    shortLabel: "そば",
    emoji: "🥢",
    switchColor: "#37474F",
    loader: () => import("../data/soba"),
    defaultVisible: false,
    defaultPinned: false,
    section: "noodles",
  },
  japanese: {
    label: "日本料理百名店",
    shortLabel: "日本料理",
    emoji: "🍱",
    switchColor: "#7B1FA2",
    loader: () => import("../data/japanese"),
    defaultVisible: false,
    defaultPinned: false,
    section: "japanese",
  },
  sushi: {
    label: "寿司百名店",
    shortLabel: "寿司",
    emoji: "🍣",
    switchColor: "#0277BD",
    loader: () => import("../data/sushi"),
    defaultVisible: false,
    defaultPinned: false,
    section: "japanese",
  },
  tempura: {
    label: "天ぷら百名店",
    shortLabel: "天ぷら",
    emoji: "🍤",
    switchColor: "#FFA000",
    loader: () => import("../data/tempura"),
    defaultVisible: false,
    defaultPinned: false,
    section: "japanese",
  },
  unagi: {
    label: "うなぎ百名店",
    shortLabel: "うなぎ",
    emoji: "🐟",
    switchColor: "#5D4037",
    loader: () => import("../data/unagi"),
    defaultVisible: false,
    defaultPinned: false,
    section: "japanese",
  },
  curry: {
    label: "カレー百名店",
    shortLabel: "カレー",
    emoji: "🍛",
    switchColor: "#D4A017",
    loader: () => import("../data/curry"),
    defaultVisible: false,
    defaultPinned: false,
    section: "rice",
  },
  shokudo: {
    label: "食堂百名店",
    shortLabel: "食堂",
    emoji: "🍚",
    switchColor: "#795548",
    loader: () => import("../data/shokudo"),
    defaultVisible: false,
    defaultPinned: false,
    section: "rice",
  },
  italian: {
    label: "イタリアン百名店",
    shortLabel: "イタリアン",
    emoji: "🍝",
    switchColor: "#388E3C",
    loader: () => import("../data/italian"),
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  french: {
    label: "フレンチ百名店",
    shortLabel: "フレンチ",
    emoji: "🍷",
    switchColor: "#3F51B5",
    loader: () => import("../data/french"),
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  spanish: {
    label: "スペイン料理百名店",
    shortLabel: "スペイン",
    emoji: "🥘",
    switchColor: "#E64A19",
    loader: () => import("../data/spanish"),
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  pizza: {
    label: "ピザ百名店",
    shortLabel: "ピザ",
    emoji: "🍕",
    switchColor: "#D32F2F",
    loader: () => import("../data/pizza"),
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  yoshoku: {
    label: "洋食百名店",
    shortLabel: "洋食",
    emoji: "🍳",
    switchColor: "#00897B",
    loader: () => import("../data/yoshoku"),
    defaultVisible: false,
    defaultPinned: false,
    section: "western",
  },
  chinese: {
    label: "中国料理百名店",
    shortLabel: "中国料理",
    emoji: "🥮",
    switchColor: "#C62828",
    loader: () => import("../data/chinese"),
    defaultVisible: false,
    defaultPinned: false,
    section: "chinese",
  },
  gyoza: {
    label: "餃子百名店",
    shortLabel: "餃子",
    emoji: "🥟",
    switchColor: "#F4511E",
    loader: () => import("../data/gyoza"),
    defaultVisible: false,
    defaultPinned: false,
    section: "chinese",
  },
  hamburger: {
    label: "ハンバーガー百名店",
    shortLabel: "ハンバーガー",
    emoji: "🍔",
    switchColor: "#6D4C41",
    loader: () => import("../data/hamburger"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  steak: {
    label: "ステーキ・鉄板焼き百名店",
    shortLabel: "ステーキ",
    emoji: "🥩",
    switchColor: "#8E0000",
    loader: () => import("../data/steak"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  sukiyaki_shabushabu: {
    label: "すき焼き・しゃぶしゃぶ百名店",
    shortLabel: "すき焼き",
    emoji: "🍲",
    switchColor: "#BF360C",
    loader: () => import("../data/sukiyaki_shabushabu"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  yakiniku: {
    label: "焼肉百名店",
    shortLabel: "焼肉",
    emoji: "🍖",
    switchColor: "#B71C1C",
    loader: () => import("../data/yakiniku"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  yakitori: {
    label: "焼き鳥百名店",
    shortLabel: "焼き鳥",
    emoji: "🍢",
    switchColor: "#E65100",
    loader: () => import("../data/yakitori"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  toriryori: {
    label: "鳥料理百名店",
    shortLabel: "鳥料理",
    emoji: "🍗",
    switchColor: "#FB8C00",
    loader: () => import("../data/toriryori"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  tonkatsu: {
    label: "とんかつ百名店",
    shortLabel: "とんかつ",
    emoji: "🐷",
    switchColor: "#8D6E63",
    loader: () => import("../data/tonkatsu"),
    defaultVisible: false,
    defaultPinned: false,
    section: "meat",
  },
  bread: {
    label: "パン百名店",
    shortLabel: "パン",
    emoji: "🥖",
    switchColor: "#A1887F",
    loader: () => import("../data/bread"),
    defaultVisible: false,
    defaultPinned: false,
    section: "bakery",
  },
  ice_gelato: {
    label: "アイス・ジェラート百名店",
    shortLabel: "アイス",
    emoji: "🍨",
    switchColor: "#EC407A",
    loader: () => import("../data/ice_gelato"),
    defaultVisible: false,
    defaultPinned: false,
    section: "bakery",
  },
  sweets: {
    label: "スイーツ百名店",
    shortLabel: "スイーツ",
    emoji: "🍰",
    switchColor: "#F06292",
    loader: () => import("../data/sweets"),
    defaultVisible: false,
    defaultPinned: false,
    section: "bakery",
  },
  wagashi: {
    label: "和菓子・甘味処百名店",
    shortLabel: "和菓子",
    emoji: "🍡",
    switchColor: "#C2185B",
    loader: () => import("../data/wagashi"),
    defaultVisible: false,
    defaultPinned: false,
    section: "bakery",
  },
  cafe: {
    label: "カフェ百名店",
    shortLabel: "カフェ",
    emoji: "☕",
    switchColor: "#4E342E",
    loader: () => import("../data/cafe"),
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  kissaten: {
    label: "喫茶店百名店",
    shortLabel: "喫茶店",
    emoji: "🫖",
    switchColor: "#3E2723",
    loader: () => import("../data/kissaten"),
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  bar: {
    label: "バー百名店",
    shortLabel: "バー",
    emoji: "🍸",
    switchColor: "#311B92",
    loader: () => import("../data/bar"),
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  izakaya: {
    label: "居酒屋百名店",
    shortLabel: "居酒屋",
    emoji: "🍶",
    switchColor: "#AD1457",
    loader: () => import("../data/izakaya"),
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  tachinomi: {
    label: "立ち飲み百名店",
    shortLabel: "立ち飲み",
    emoji: "🍻",
    switchColor: "#FFA726",
    loader: () => import("../data/tachinomi"),
    defaultVisible: false,
    defaultPinned: false,
    section: "drinks",
  },
  creative_innovative: {
    label: "創作料理・イノベーティブ百名店",
    shortLabel: "創作",
    emoji: "✨",
    switchColor: "#00838F",
    loader: () => import("../data/creative_innovative"),
    defaultVisible: false,
    defaultPinned: false,
    section: "other",
  },
  okonomiyaki: {
    label: "お好み焼き百名店",
    shortLabel: "お好み焼き",
    emoji: "🥞",
    switchColor: "#FF8F00",
    loader: () => import("../data/okonomiyaki"),
    defaultVisible: false,
    defaultPinned: false,
    section: "other",
  },
  asia_ethnic: {
    label: "アジア・エスニック百名店",
    shortLabel: "エスニック",
    emoji: "🌶️",
    switchColor: "#558B2F",
    loader: () => import("../data/asia_ethnic"),
    defaultVisible: false,
    defaultPinned: false,
    section: "other",
  },
} as const satisfies Record<string, CategoryConfig>;

export type CategoryKey = keyof typeof CATEGORIES;

export const CATEGORY_KEYS = Object.keys(CATEGORIES) as CategoryKey[];
