name: Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Biome check
        run: npx biome check .
